In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder

In [ ]:
data=pd.read_csv('iris.csv')

In [ ]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
le=StandardScaler()
columns=['sepal_length','sepal_width','petal_length','petal_width']
new=le.fit_transform(data[columns])
new1=pd.DataFrame(new,columns=columns)
data.drop(columns,axis=1,inplace=True)
data=pd.concat([data,new1],axis=1)
data

       species  sepal_length  sepal_width  petal_length  petal_width
0       setosa     -0.900681     1.032057     -1.341272    -1.312977
1       setosa     -1.143017    -0.124958     -1.341272    -1.312977
2       setosa     -1.385353     0.337848     -1.398138    -1.312977
3       setosa     -1.506521     0.106445     -1.284407    -1.312977
4       setosa     -1.021849     1.263460     -1.341272    -1.312977
..         ...           ...          ...           ...          ...
145  virginica      1.038005    -0.124958      0.819624     1.447956
146  virginica      0.553333    -1.281972      0.705893     0.922064
147  virginica      0.795669    -0.124958      0.819624     1.053537
148  virginica      0.432165     0.800654      0.933356     1.447956
149  virginica      0.068662    -0.124958      0.762759     0.790591

[150 rows x 5 columns]

In [ ]:
le1=LabelEncoder()
le2=le1.fit_transform(data['species'])
le2=pd.DataFrame(le2,columns=['species'])
data.drop('species',axis=1,inplace=True)
data=pd.concat([data,le2],axis=1)
data

     sepal_length  sepal_width  petal_length  petal_width  species
0       -0.900681     1.032057     -1.341272    -1.312977        0
1       -1.143017    -0.124958     -1.341272    -1.312977        0
2       -1.385353     0.337848     -1.398138    -1.312977        0
3       -1.506521     0.106445     -1.284407    -1.312977        0
4       -1.021849     1.263460     -1.341272    -1.312977        0
..            ...          ...           ...          ...      ...
145      1.038005    -0.124958      0.819624     1.447956        2
146      0.553333    -1.281972      0.705893     0.922064        2
147      0.795669    -0.124958      0.819624     1.053537        2
148      0.432165     0.800654      0.933356     1.447956        2
149      0.068662    -0.124958      0.762759     0.790591        2

[150 rows x 5 columns]

In [ ]:
X=data.drop('species',axis=1)
y=data['species']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
model=SVC()
model.fit(X_train,y_train)

SVC()

In [ ]:
result=model.predict(X_test)

In [ ]:
result

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
print("accurancy",accuracy_score(y_test,result))

accurancy 1.0